comment([şu,ana,kadar,izlediğim,en,iyi,film,diyebilirim,gerçekten,mükemmel],10).
comment([mutheşem,ve,enfes,bir,yapım,uzun,yıllar,boyunca,hafızalardan,silinmeyeceğine,eminim],10).
comment([son,derece,kalite,kokmak,ben,rus],9).
comment([güzel,bir,film,gerçekten,yapanın,eline,sağlık],9).
comment([bu,filmi,çok,beğendim,ama,süresi,çok,uzundu,herkese,tavsiye,ederim],8).
comment([bölgeyi,bilmeyenlere,anlatmayı,vaat,eden,oldukça,iyi,bir,film],8).
comment([izlerken,insanı,ürperten,bir,film,bunu,o,şartlarda,yaşayanlar,bilebilir,ancak],8).
comment([türklerin,böyle,filmleri,daha,fazla,yapması,gerekiyor,ki,kaliteyi,dahada,yukarı,çekebilsin,filme,gelecek,olursak,güzel,izlenebilir,bir,yapım],7).
comment([orta,seviye,bence,ne,eksik,ne,fazla],5).
comment([kısaca,kötü,ama,bu,iş,görmez,demek,değil,tabi],3).
comment([ne,göstermek,istenildiğini,hala,çözemedim,anlamak,zor],2).
comment([ah,o,eski,film,seyir,zevki,ah],2).
comment([berbat,bir,şey,neden,böyle,bir,girişimde,bulunulmuş,anlamak,zor],1).
comment([tamamen,vakit,kaybı,kurgusundan,oyuncu,seçimine,diyaloglarından,mantık,hatalarına,kadar,her,yönüyle,saçma,yetersiz,bir,film],1).
comment([harika,diğer,sonlara,benzemeyen,bir,son,bazı,filmler,var,ki,kalbe,dokunuyor,bu,bilimkurgu,da,olsa],10).
comment([bu,kadar,iyi,bir,film,ve,iyi,bir,seri,bir,daha,gelir,mi,bilemiyorum,muhteşem],10).
comment([sinema,tarihinin,en,kusursuz,yapimi,hala,daha,daha,iyisi,gelmedi,herseyiyle,tam,bir,basyapit],10).
comment([kesinlikle,izlenmesi,gereken,bir,aksiyon,ve,bilim_kurgu,filmi],8).
comment([bence,gayet,hoş,bir,film,gülmek,için,gidilirse,gerçekten,güldürüyor],8).
comment([çok,beğendiğim,ve,sevdiğim,filmlerden,birisidir,eğer,izlemeyen,arkadaşlar,varsa,kesinlikle,izlesinler],9).
comment([son,zamanlarda,izlediğim,en,en,güzel,filmdi,dolu,dolu,gülmek,duygulanmak,istiyorsanız,kesinlikle,izleyin,derim],8).
comment([son,zamanlarda,bu,kadar,iyi,bir,aksiyon,ve,komedi,filmi,izlememiştim,herkesin,eline,sağlık],8).
comment([gayet,eğlenceli,ve,izlenebilir,bir,film,şu,zamanda,vizyonda,yer,alan,filmlerden,en,iyisi,sayılabilir],8).
comment([çok,keyifli,eğlenceli,birazda,dram,içeren,güzel,bir,film,verdiğiniz,paraya,değer],7).
comment([ben,filmden,keyif,aldım,en,az,shaun,of,the,dead,kadar,komik,ve,eğlenceli,idi],7).
comment([sinema,tarihinin,en,kötü,filmlerinden,biriyle,karşı,karşıyayız,hiç,zevk,almadım],1).
comment([harbiden,şaka,gibi,fıkra,gibi,bi,film,bundan,kötüsü,olamaz,herhalde,imdb,bile,farkına,varmış,olacak,en,kötü,filmler,arasına,koymuş,bunu],1).
comment([saka,gibi,bir,film],1).
comment([rezil,ötesi,bir,film],1).
comment([gayet,kötü,bir,film,tavsiye,edilecek,bir,tarafı,yok,anlamsız,ve,boş],1).
comment([bunu,izledim,diye,kendimden,nefret,ettim,kötü,tarafa,geçmek,üzereyim],1).
comment([şu,an,bu,filme,diyecek,şeylerim,olumsuz,sıfatlardan,oluşuyor,acemice,usülsüz,kalitesiz,beceriksiz,salakça,emeksiz],1).
comment([orta,seviye,bir,bütçeyle,çekilmiş,normal,oyunculara,sahip,seviyeli,bir,film],6).
comment([iyi,ki,izlemişim,dedim,sinema,salonundan,çıkarken,gerçekten,izlemeye,değer],8).
comment([enfes,oyunculuklar,geniş,bütçe,mükemmel,kurgu,tek,kelimeyle,harika],10).
comment([ölmek,istedim,izlerken,yarısında,çıktım,zamanım,o,kadar,değersiz,değilmiş],1).
comment([tekrar,izlemek,istemem,ama,akıcı,bir,film,başladınız,mı,bittiğini,anlamıyorsunuz],5).
comment([zaman,öldürmek,için,uygun,canınızı,sıkmadan,izleyebilirsiniz],5).
comment([keşke,diğer,filme,gitseydim,diye,sonsuza,kadar,hayıflanacağım],2).
comment([hiç,bir,mesaj,içermeyen,düşüncesiz,fikirsiz,insanların,yapımı,olan,bu,filmi,izlemeyin],1).
comment([doğru,söylemek,gerekirse,oldukça,iyi,bir,film,aleyhine,eleştirmek,zor],8).
comment([günlük,hayattan,uzaklaştıran,kafa,boşaltan,rahatlatan,orta,seviyede,bir,yapım],5).
comment([özellikle,bu,filmi,aylardır,bekliyordum,beklediğime,değdi,kesinlikle,kalteli,ve,akıcı,gerçekten,iyi],9).
comment([bazen,güzel,işler,ortaya,çıkıyor,bu,film,buna,örnek],7).
comment([göz,açıp,kapayana,kadar,bitti,güzel,ama,çok,kısa],8).
comment([kadın,baş,rol,oyuncusu,mükemmel,bir,performans,sergiledi,diğerleri,için,orta,seviye,diyebilirim],8).
comment([izlememiş,olanları,kıskanıyorum,ne,olacağını,bilmeden,bir,daha,izlemek,istiyorum],8).
comment([ruhsuz,renksiz,tadı,tuzu,olmayan,vaktimden,çalan,boş,bir,yapıt],2).
comment([hem,öğretici,hem,sorgulayan,insanı,düşünmek,zorunda,bırakan,özel,bir,film],9).
comment([anne,ve,baba,figürü,olmadan,yetişen,çocukların,gözlerinden,dünyaya,bakmamızı,sağlayan,derin,ve,güzel,bir,film],9).